name: COPY FILES
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy to Windows
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          #  key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
          tar_dereference: true
          rm: true
